### ISSUE TITLE
Simpler patching abstraction

### ISSUE THREAD

**Issue by iloveitaly** [adamchainz/patchy#541]
### Description

```python
def patch_me():
    print("unpatched")

def patched():
    print("patched")


def replace_first_method_name(code, new_name):
    return re.sub(r"^def\s+\w+\(", f"def {new_name}(", code, count=1)

patchy.replace(
    patch_me,
    inspect.getsource(patch_me),
    None,
    replace_first_method_name(inspect.getsource(patched), patch_me.__name__),
)
```

**Comment by adamchainz** [comment]
I don‘t understand what you’re proposing. It seems you’re just showing a way of using the existing `replace()` method. Please use words to describe an issue and its motivation, not just code.

**Comment by iloveitaly** [comment]
Sorry, description got wiped out by gh-cli.

Goals:

* Test/type patched method. Can't do this when passing the source code as a string.
* Include patched source, file location, etc in `linecache` for debugging
* Pass a function reference to patchy, this ensures syntax is correct
* Assert AST of the patched method without having to include the source in the patchy call

The above method seems to work to solve these issues. I'm curious if you are open to adding the above logic to the core library (I can submit a PR with tests) so something like this is possible:

```
def patch_me():
    print("unpatched")

def patched():
    print("patched")

patchy.replace(patch_me, patched)
```

Probably makes sense to have a separate `patchy` method for this, but could also sniff out the types in the `replace` params instead.

What do you think?

**Comment by adamchainz** [comment]
You don’t need patchy for what you’re proposing. You can just assign the `__code__` object of your patched function onto the `patch_me()` function.

```ipython
In [1]: def patch_me():
   ...:     print("unpatched")
   ...:
   ...: def patched():
   ...:     print("patched")
   ...:

In [2]: patch_me.__code__ = patched.__code__

In [3]: patch_me
Out[3]: <function __main__.patch_me()>

In [4]: patch_me()
patched
```

And you can write a test or `assert` statement to ensure that `inspect.getsource(patch_me)` matches the original source you expect.

The main use case of patchy is to patch upstream packages when your project starts up. It checks the upstream hasn’t changed in unexpected ways whilst being robust to irrelevant ones. The syntax is guaranteed correct because it compiles the source at that point. You can test the patched functions for their behaviour post-patch because your tests should run after the patching.

Hope that helps,

Adam
